// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emxrnoibbfuqexcbrnxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteHJub2liYmZ1cWV4Y2Jybnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzM2OTQsImV4cCI6MjA2ODYwOTY5NH0.zXPif2w5jQ2ZEdeU4vy45avnK-8Y_xZvDlmFKeE5OM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});